<a href="https://colab.research.google.com/github/Valerie231/ML_homeworks/blob/main/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np

In [ ]:
vector = np.array(np.random.rand(10))

In [ ]:
matrix = np.matrix([[11,14,17], [20,23,26], [29,32,35]])

In [ ]:
vector.shape, matrix.shape

((10,), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
np.round(vector+10, 2)

array([10.95, 10.38, 10.02, 10.74, 10.82, 10.7 , 10.57, 10.91, 10.45,
       10.46])

In [ ]:
matrix*2

matrix([[22, 28, 34],
        [40, 46, 52],
        [58, 64, 70]])

In [ ]:
new_v = vector**2
vector, new_v

(array([0.95151524, 0.37867198, 0.01520659, 0.74410732, 0.82001544,
        0.70217703, 0.56647714, 0.911434  , 0.45307068, 0.45882412]),
 array([9.05381248e-01, 1.43392466e-01, 2.31240492e-04, 5.53695705e-01,
        6.72425321e-01, 4.93052578e-01, 3.20896348e-01, 8.30711944e-01,
        2.05273044e-01, 2.10519577e-01]))


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

I transposed matrices so that now we have (2,3) and (3,2) shaped matrices and therefore the result will have shape (2,2).

In [ ]:
result_matrix = np.dot(A.T, B.T)
result_matrix

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

We will get 2x1 matrix because we multiply (2,2) by (2,1)

In [ ]:
np.dot(result_matrix, C)

array([[0.2034],
       [0.2846]])

By multiplying 2x2 matrix by another 2x2 matrix we get 2x2 matrix

In [ ]:
np.dot(result_matrix, D)

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
result_matrix.T

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [ ]:
vector.T, vector.shape, vector.T.shape

(array([0.95151524, 0.37867198, 0.01520659, 0.74410732, 0.82001544,
        0.70217703, 0.56647714, 0.911434  , 0.45307068, 0.45882412]),
 (10,),
 (10,))

There is no difference because vector is one-dimensional

In [ ]:
column_vector = np.expand_dims(vector, axis=1)
vector, column_vector

(array([0.95151524, 0.37867198, 0.01520659, 0.74410732, 0.82001544,
        0.70217703, 0.56647714, 0.911434  , 0.45307068, 0.45882412]),
 array([[0.95151524],
        [0.37867198],
        [0.01520659],
        [0.74410732],
        [0.82001544],
        [0.70217703],
        [0.56647714],
        [0.911434  ],
        [0.45307068],
        [0.45882412]]))

In [ ]:
column_vector.shape

(10, 1)

The new vector is now two-dimentional

In [ ]:
column_vector, column_vector.T

(array([[0.95151524],
        [0.37867198],
        [0.01520659],
        [0.74410732],
        [0.82001544],
        [0.70217703],
        [0.56647714],
        [0.911434  ],
        [0.45307068],
        [0.45882412]]),
 array([[0.95151524, 0.37867198, 0.01520659, 0.74410732, 0.82001544,
         0.70217703, 0.56647714, 0.911434  , 0.45307068, 0.45882412]]))

In [ ]:
column_vector.shape, column_vector.T.shape

((10, 1), (1, 10))

Now we see the difference, because the new vector has two dimentions so we can transpose it